apiVersion: copa.sh/v1alpha1
kind: PatchConfig
images:
  - name: "debian-multiarch-test"
    image: "__DEBIAN_REPO__"
    tags:
      strategy: "list"
      list: ["12.4-slim"]
    platforms: ["linux/amd64", "linux/arm/v7"]
    target:
      tag: "{{ .SourceTag }}-patched-e2e"
